version: '3.8'

services:
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      # Проверка каждые 5 минут
      - WATCHTOWER_POLL_INTERVAL=300

      # Уведомления (настроить SLACK_WEBHOOK в .env)
      # - WATCHTOWER_NOTIFICATIONS=slack
      # - WATCHTOWER_NOTIFICATION_SLACK_HOOK_URL=${SLACK_WEBHOOK}

      # Cleanup старых образов
      - WATCHTOWER_CLEANUP=true

      # Мониторить только наши контейнеры
      - WATCHTOWER_LABEL_ENABLE=true
    labels:
      - com.centurylinklabs.watchtower.enable=false
