name: Deploy to Staging

on:
  push:
    branches:
      - staging  # Автодеплой только при push в staging

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Test summary
        run: echo "✅ All tests passed"

  build-and-deploy:
    name: Build and Deploy to Staging
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push staging image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/quote-calculator:staging
            ${{ secrets.DOCKER_USERNAME }}/quote-calculator:staging-${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/quote-calculator:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/quote-calculator:buildcache,mode=max

      - name: Deploy to staging server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /opt/quote-calculator
            
            echo "📦 Deploying to STAGING..."
            
            # Pull новый staging образ
            docker pull ${{ secrets.DOCKER_USERNAME }}/quote-calculator:staging
            
            # Restart staging контейнера
            docker-compose up -d quote-staging
            
            # Health check
            sleep 10
            curl -f http://localhost:3006/health || exit 1
            
            echo "✅ Staging deployment successful!"

      - name: Notify success
        if: success()
        run: |
          echo "✅ Staging deployment successful!"
          echo "🔗 Staging URL: http://${{ secrets.SERVER_HOST }}:3006"

      - name: Notify failure
        if: failure()
        run: |
          echo "❌ Staging deployment failed!"
          exit 1
